name = "proxy"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

vars = { ENDPOINT = "https://graphql.fauna.com/graphql" }
# kv-namespaces = [
#   { binding = "FAUNA_STORE", id = "" }
# ]
